In [ ]:
Дан файл с таблицей в формате TSV (англ. tab separated values — значения, разделённые табуляцией) с информацией о росте школьников разных классов.

Напишите программу, которая прочитает этот файл и подсчитает для каждого класса средний рост учащегося.

Файл состоит из набора строк, каждая из которых представляет собой три поля:
Класс Фамилия Рост

Класс обозначается только числом. Буквенные модификаторы не используются. Номер класса может быть от 1 до 11 включительно. В фамилии нет пробелов, а в качестве роста используется натуральное число, но при подсчёте среднего требуется вычислить значение в виде вещественного числа.

Выводить информацию о среднем росте следует в порядке возрастания номера класса (для классов с первого по одиннадцатый). Если про какой-то класс нет информации, необходимо вывести напротив него прочерк, например:

Sample Input:
6	Вяххи	159
11	Федотов	172
7	Бондарев	158
6	Чайкина	153
Sample Output:
1 -
2 -
3 -
4 -
5 -
6 156.0
7 158.0
8 -
9 -
10 -
11 172.0

In [23]:
in_fname = "dataset_3380_5.txt"
in_f = open(in_fname, 'r')
pup_h = {}
for i in range(1, 12):
    pup_h[str(i)]=[0, 0]
print(pup_h)

{'1': [0, 0], '2': [0, 0], '3': [0, 0], '4': [0, 0], '5': [0, 0], '6': [0, 0], '7': [0, 0], '8': [0, 0], '9': [0, 0], '10': [0, 0], '11': [0, 0]}

In [24]:
for line in in_f: 
    row = line.strip().split('\t')
    print(row)
    # pup_h[row[0]] = [pup_h[row[0]][0] + 1, pup_h[row[0]][1] + row[2]]
    pup_h[row[0]] = [pup_h[row[0]][0] + 1, pup_h[row[0]][1] + int(row[2])]
print (pup_h)

['4', 'Johnson', '143']
['7', 'Allford', '158']
['2', 'Charlson', '126']
['10', 'Dunce', '173']
['1', 'Gardner', '126']
['3', 'Attwood', '133']
['4', 'Philips', '138']
['2', 'Anderson', '131']
['5', 'Marlow', '146']
['11', 'Chapman', '174']
['11', 'Birch', '173']
['2', 'Ferguson', '130']
['10', 'Leapman', '171']
['10', 'Turner', '166']
['4', 'Forman', '143']
['2', 'Aldridge', '128']
['2', 'Kirk', '125']
['9', 'Chapman', '168']
['5', 'Lawman', '143']
['4', 'Lewin', '145']
['9', 'James', '171']
['9', 'Ramacey', '165']
['9', 'Flatcher', '169']
['8', 'Samuels', '163']
['10', 'Douglas', '169']
['5', 'Quincy', '141']
['8', 'Shorter', '168']
['2', 'Fraser', '135']
['11', 'Bishop', '178']
['6', 'Molligan', '151']
['1', 'Bootman', '124']
['1', 'Parson', '123']
['5', 'Winter', '143']
['9', 'Flatcher', '170']
['2', 'Alsopp', '131']
['5', 'Creighton', '147']
['6', 'Dowman', '152']
['11', 'Dodson', '175']
['10', 'Aldridge', '173']
['7', 'Fitzgerald', '159']
['7', 'Archibald', '161']
['9', 'Ryder', '174']
['8', 'Oldridge', '165']
['7', 'Audley', '162']
['9', 'Stephen', '170']
['6', 'Eddington', '160']
['8', 'Stevenson', '165']
['5', 'Wayne', '140']
['4', 'White', '140']
['1', 'Stephen', '121']
['1', 'Abramson', '121']
['1', 'Calhoun', '123']
['8', 'Shorter', '168']
['2', 'Adrian', '126']
['8', 'Parkinson', '162']
['9', 'Fisher', '172']
['10', 'Black', '169']
['11', 'Larkins', '170']
['4', 'Jenkin', '145']
['2', 'Bradberry', '132']
['1', 'Peacock', '124']
['6', 'Simon', '151']
['11', 'Dutton', '174']
['2', 'Blomfield', '130']
['3', 'Farmer', '135']
['5', 'Ogden', '150']
['6', 'MacAlister', '154']
['3', 'Gilson', '137']
['6', 'Fane', '154']
['2', 'Morrison', '135']
['7', 'Howard', '157']
['7', 'Fitzgerald', '164']
['9', 'Barnes', '169']
['11', 'Thorndike', '172']
['1', 'Wesley', '128']
['4', 'Adderiy', '137']
['1', 'Finch', '123']
['4', 'Dickinson', '137']
['4', 'Webster', '145']
['2', 'Carter', '135']
['6', 'Wood', '150']
['1', 'Ogden', '126']
['1', 'Carter', '120']
{'1': [11, 1359], '2': [12, 1564], '3': [3, 405], '4': [9, 1273], '5': [7, 1010], '6': [7, 1072], '7': [6, 961], '8': [6, 991], '9': [9, 1528], '10': [6, 1021], '11': [7, 1216]}

In [25]:
for i in range(1, 12):
    if pup_h[str(i)][0] == 0:
        print(i, '-')
    else:
        print(i, pup_h[str(i)][1] / pup_h[str(i)][0])

1 123.54545454545455
2 130.33333333333334
3 135.0
4 141.44444444444446
5 144.28571428571428
6 153.14285714285714
7 160.16666666666666
8 165.16666666666666
9 169.77777777777777
10 170.16666666666666
11 173.71428571428572